package com.proyecto.api.ecommerceapiv2.util.enums.auth;

public enum RolePermissionEnum {
    //PERMISOS PARA PRODUCTO
    READ_ALL_PRODUCTS,
    READ_ONE_PRODUCT,
    CREATE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DISABLE_ONE_PRODUCT,

    //PERMISOS PARA CATEGORÍA
    READ_ALL_CATEGORIES,
    READ_ONE_CATEGORY,
    CREATE_ONE_CATEGORY,
    UPDATE_ONE_CATEGORY,
    DISABLE_ONE_CATEGORY,

    //PERMISO PARA VER MI PERFIL
    READ_MY_PROFILE;
}
